services:

  db:
    container_name: db
    image: mysql:8.0.32
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - test_day

  php:
    container_name: php
    build:
      context: ./docker/images/php
    volumes:
      - ./:/var/www/html
    networks:
      - test_day

  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - php
    volumes:
      - ./public:/var/www/html/public
      - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs:/var/log/nginx
    networks:
      - test_day
    ports:
      - "80:80"

volumes:
  data:

networks:
  test_day:
